version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
